# Generated by Django 3.2 on 2021-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_app', '0003_alter_transaction_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
